### ISSUE TITLE
Files on GitHub are compressed

### ISSUE THREAD

**Issue by Jonskichov** [BSData/maelstroms-edge#2]
Looks like the data files here on GitHub are the compressed (catz/gstz) versions. These won't work with the data site.

You'll need to replace them with the uncompressed (cat/gst) versions.

You can save the files as such from Data Editor (save as...)

**Comment by MattunR** [comment]
So I am quite at a loss. When I try to get my data from the appspot site, I keep getting this:

"Error: Server Error
The server encountered an error and could not complete your request.

Please try again in 30 seconds."

I saved my files as .gst and .cat, uploaded and newly released. I can download the, say, 40k files just fine, but they're all catz files?

**Comment by MattunR** [comment]
Well, don't know what it was all about, but it works now.
