### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MaelstromsEdge** [BSData/maelstroms-edge#4]
### Your Discord

insaniak#9353

### Additional information

I'm looking to take over the handling of the Maelstrom's Edge repository as the person who was updating it previously no longer has time to do so.

**Comment by Mad-Spy** [comment]
/invite MaelstromsEdge

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/1286200231)
:robot: Invited @MaelstromsEdge with **push** access. Invite can be accepted on https://github.com/BSData/maelstroms-edge/invitations
